BEGIN
	DECLARE @Nome VarChar(30)
	SET @Nome = 'CWI Software'
	Print @Nome
END

BEGIN
	DECLARE ListaCidade CURSOR
		Local
		Fast_Forward
		FOR Select Nome, Uf
			From Cidade
			Group by Nome, Uf
			Having COUNT(1) > 1;
	
	DECLARE @vNome varchar(50),
				@vUF varchar(2)
	OPEN ListaCidade;
	FETCH NEXT FROM ListaCidade INTO @vNome, @vUF
	
	WHILE (@@FETCH_STATUS=0) BEGIN
		Print @vNome + '/'+@vUF;
		FETCH NEXT FROM ListaCidade INTO @vNome, @vUF
	END
	
	CLOSE ListaCidade;
	DEALLOCATE ListaCidade;
END
--------------------------------------------------------------------------
--1
BEGIN
	DECLARE @vIDPRODUTO VARCHAR(10),
			@vNOMEPROD VARCHAR(10),
			@vDATACADASTRO VARCHAR(10),
			@vPRECOCUSTO VARCHAR(10),
			@vPRECOVENDA VARCHAR(10),
			@vSITUACAO VARCHAR(10),
			@vQUANTIDADE INT

	SELECT TOP 1 @vIDPRODUTO = P.IDPRODUTO, @vNOMEPROD = P.NOME, @vDATACADASTRO = P.DATACADASTRO,
				 @vPRECOCUSTO = P.PRECOCUSTO, @vPRECOVENDA = P.PRECOVENDA, @vSITUACAO = P.SITUACAO, 
				 @vQUANTIDADE = COUNT(1)
	FROM PEDIDOITEM PI
	LEFT JOIN PRODUTO P ON PI.IDPRODUTO = P.IDPRODUTO
	GROUP BY P.IDPRODUTO, P.NOME, P.DATACADASTRO, P.PRECOCUSTO, P.PRECOVENDA, P.SITUACAO
	ORDER BY COUNT(1) DESC

	PRINT 'ID: ' + @vIDPRODUTO
	PRINT 'NOME: ' + @vNOMEPROD
	PRINT 'DATA CADASTRO: ' + @vDATACADASTRO
	PRINT 'CUSTO: ' + @vPRECOCUSTO
	PRINT 'VENDA: ' + @vPRECOVENDA
	PRINT 'SITUACAO: ' + @vSITUACAO
	PRINT 'QTD VENDAS: ' + CAST( @vQUANTIDADE AS VARCHAR(10))

END
--------------------------------------------------------------------------
--2
BEGIN
	DECLARE ListaCidade CURSOR
		LOCAL
		FAST_FORWARD
		FOR SELECT NOME
			FROM CIDADE
			WHERE IDCIDADE IN (SELECT IDCIDADE
							   FROM CLIENTE)
			GROUP BY NOME, UF
			HAVING COUNT(1) > 1;

	DECLARE @vCIDADE VARCHAR(20)

	OPEN ListaCidade;
	FETCH NEXT FROM ListaCidade INTO @vCIDADE

	WHILE (@@FETCH_STATUS = 0) BEGIN
		PRINT @vCIDADE;
		FETCH NEXT FROM ListaCidade INTO @vCIDADE	
	END

	CLOSE ListaCidade;
	DEALLOCATE ListaCidade;
END
--------------------------------------------------------------------------
--3
BEGIN
	DECLARE @vMATERIALUSADO INT

	SELECT TOP 1 @vMATERIALUSADO = IDMATERIAL
	FROM PRODUTOMATERIAL
	GROUP BY IDMATERIAL
	ORDER BY COUNT(1) DESC

	DECLARE @vIDCIDADE INT,
			@vVENDAS INT,
			@vULTIMASVENDAS INT

	DECLARE LISTAPRODUTOS CURSOR
		LOCAL
		FAST_FORWARD
		FOR SELECT IDPRODUTO
			FROM PRODUTOMATERIAL
			WHERE IDMATERIAL = @vMATERIALUSADO

		OPEN LISTAPRODUTOS;
		FETCH NEXT FROM LISTAPRODUTOS INTO @vIDCIDADE

		WHILE (@@FETCH_STATUS = 0) BEGIN
			SELECT @vVENDAS = COUNT(1)
			FROM PEDIDOITEM
			WHERE IDPRODUTO = @vIDCIDADE

			PRINT 'ID CIDADE: ' + CAST(@vIDCIDADE AS VARCHAR(20)) + ' VENDAS: ' + CAST(@vVENDAS AS VARCHAR(10))
			FETCH NEXT FROM LISTAPRODUTOS INTO @vIDCIDADE
		END	

	CLOSE LISTAPRODUTOS;
	DEALLOCATE LISTAPRODUTOS;

	DECLARE @vTOTALVENDAS VARCHAR(20)

	SELECT @vTOTALVENDAS = SUM(VALORPEDIDO)
	FROM PEDIDO
	WHERE DATAPEDIDO BETWEEN (GETDATE() - 60) AND GETDATE()

	PRINT 'QUANTIDADE TOTAL DE VENDAS (60 DIAS) R$ ' + @vTOTALVENDAS

END


--------------------------------------------------------------------------

--4

BEGIN
	DECLARE @vIDCLIENTE INT,
			@vNOMECLIENTE VARCHAR(20),
			@vID_CIDADE INT,
			@vNOMECIDADE VARCHAR(20)
	DECLARE LISTACLIENTE CURSOR
		LOCAL
		FAST_FORWARD
		FOR SELECT CL.IDCLIENTE, CL.NOME NOME_CLIENTE, CL.IDCIDADE, C.NOME AS NOME_CIDADE
			FROM CLIENTE CL
				LEFT JOIN CIDADE C ON CL.IDCIDADE = C.IDCIDADE
			WHERE CL.IDCIDADE IN (SELECT MAX(IDCIDADE)
							   FROM CIDADE
							   GROUP BY NOME,UF
							   HAVING COUNT(1) > 1);

		OPEN LISTACLIENTE;
		FETCH NEXT FROM LISTACLIENTE INTO @vIDCLIENTE, @vNOMECLIENTE, @vID_CIDADE, @vNOMECIDADE

		WHILE (@@FETCH_STATUS = 0) BEGIN
			
			PRINT 'IDCLIENTE: ' + CAST(@vIDCLIENTE AS VARCHAR(10)) + 
				  '. NOME_CLIENTE: '+ @vNOMECLIENTE +
				  '. IDCIDADE: ' + CAST(@vID_CIDADE AS VARCHAR(10)) +
				  '. NOME_CIDADE: ' + @vNOMECIDADE + '.'
			FETCH NEXT FROM LISTACLIENTE INTO @vIDCLIENTE, @vNOMECLIENTE, @vID_CIDADE, @vNOMECIDADE
		END

	CLOSE LISTACLIENTE;
	DEALLOCATE LISTACLIENTE;
END