--1
SELECT COUNT(DISTINCT SITUACAO)
FROM PRODUTO;
---------------------------------------------------------------
--2
SELECT NOME
FROM CLIENTE
WHERE NOME LIKE '%LTDA%' OR RAZAOSOCIAL LIKE '%LTDA%';
---------------------------------------------------------------
--3
INSERT INTO PRODUTO 
	(NOME, DATACADASTRO, PRECOCUSTO,PRECOVENDA, SITUACAO) 
	VALUES
	('Galocha Maragato', GETDATE(), 35.67, 77.95, 'A');
---------------------------------------------------------------
--4
SELECT *
FROM PRODUTO
WHERE IDPRODUTO NOT IN (
				SELECT IDPRODUTO
				FROM PEDIDOITEM)
---------------------------------------------------------------
--5
SELECT TOP 1 C.UF, COUNT(1) AS TOTAL_CLIENTES
FROM CIDADE C
	LEFT JOIN CLIENTE CL ON CL.IDCIDADE = C.IDCIDADE
GROUP BY C.UF
HAVING COUNT(1) = ( SELECT TOP 1 COUNT(1) AS TOTAL_CLIENTES
					FROM CIDADE C
					LEFT JOIN CLIENTE CL ON CL.IDCIDADE = C.IDCIDADE
					GROUP BY C.UF
					ORDER BY COUNT(1) DESC)

UNION ALL

SELECT TOP 1 C.UF, COUNT(1) AS TOTAL_CLIENTES
FROM CIDADE C
	LEFT JOIN CLIENTE CL ON CL.IDCIDADE = C.IDCIDADE
GROUP BY C.UF
HAVING COUNT(1) = ( SELECT TOP 1 COUNT(1) AS TOTAL_CLIENTES
					FROM CIDADE C
					LEFT JOIN CLIENTE CL ON CL.IDCIDADE = C.IDCIDADE
					GROUP BY C.UF
					ORDER BY COUNT(1))
---------------------------------------------------------------
--6
SELECT COUNT(DISTINCT C.NOME)
FROM PEDIDO P
	LEFT JOIN CLIENTE CL ON P.IDCLIENTE = CL.IDCLIENTE
	LEFT JOIN CIDADE C ON CL.IDCIDADE = C.IDCIDADE
---------------------------------------------------------------